baseURL = 'https://matteocroce.it/'
languageCode = 'en-US'
title = 'Matteo Croce personal homepage'

theme = ['hugo-bearblog']
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Curriculum"
    url = "/cv.pdf"
    weight = 2

  [[menu.main]]
    name = "Open-source"
    url = "/open-source/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

[params]
author = 'Matteo (teknoraver) Croce'
copyright = 'Matteo Croce'
favicon = 'imgs/gear.svg'
hideMadeWithLine = true
images = ['imgs/matteo.jpg']

[markup.goldmark.renderer]
unsafe = true
